name: katalogDT
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  sqflite: ^2.3.0
  path: ^1.9.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # 1. Tambahkan package ini di dev_dependencies
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

# 2. Tambahkan konfigurasi ini di bagian paling bawah (sejajar dengan baris flutter:)
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF" # Warna background jika logo kamu transparan/bulat