name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      # Men-generate platform android dan mengubah package name secara otomatis
      - name: Create Android Platform & Ganti Package Name
        run: |
          echo "📝 Memperbaiki nama project di pubspec.yaml agar lowercase..."
          sed -i 's/^name:.*/name: katalog_dt/' pubspec.yaml

          if [ ! -d "android" ]; then
            echo "⚠️ Folder android tidak ditemukan. Men-generate folder native..."
            flutter create . --project-name=katalog_dt --platforms=android
          fi

          # Mencari file build.gradle atau build.gradle.kts langsung di folder android/app/
          TARGET_FILE=$(find android/app/ -name "build.gradle*" | head -n 1)

          if [ -z "$TARGET_FILE" ]; then
            echo "❌ ERROR: File konfigurasi Gradle tidak ditemukan!"
            exit 1
          else
            echo "✅ File ditemukan di: $TARGET_FILE"
            # Mengubah ID aplikasi untuk format Groovy (spasi) maupun Kotlin DSL (sama dengan)
            sed -i 's/applicationId\s*=\s*".*"/applicationId = "com.client.babeinfo"/' "$TARGET_FILE"
            sed -i 's/applicationId\s*".*"/applicationId "com.client.babeinfo"/' "$TARGET_FILE"
            echo "✅ Sukses mengubah package name menjadi com.client.babeinfo"
          fi

      - name: Install Dependencies
        run: flutter pub get

      - name: Generate Launcher Icons
        run: dart run flutter_launcher_icons || echo "Launcher icons skip, lanjut build..."

      - name: Build APK Release
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Katalog-PO-Release-APK
          path: build/app/outputs/flutter-apk/*.apk
