name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      # Mengubah ID Aplikasi secara paksa sebelum dicompile
      - name: Ganti Package Name via Linux sed
        run: |
          sed -i 's/applicationId ".*"/applicationId "com.client.babeinfo"/' android/app/build.gradle

      - name: Generate Launcher Icons
        run: dart run flutter_launcher_icons || echo "Launcher icons skip / gagal, lanjut build..."

      - name: Build APK Release
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Katalog-PO-Release-APK
          path: build/app/outputs/flutter-apk/*.apk
